USE [master]
GO
/****** Object:  Database [Ctrl_Escolar]    Script Date: 17/01/2022 10:09:39 a. m. ******/
CREATE DATABASE [Ctrl_Escolar]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Ctrl_Escolar', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Ctrl_Escolar.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Ctrl_Escolar_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Ctrl_Escolar_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [Ctrl_Escolar] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Ctrl_Escolar].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Ctrl_Escolar] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Ctrl_Escolar] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Ctrl_Escolar] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Ctrl_Escolar] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Ctrl_Escolar] SET ARITHABORT OFF 
GO
ALTER DATABASE [Ctrl_Escolar] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [Ctrl_Escolar] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Ctrl_Escolar] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Ctrl_Escolar] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Ctrl_Escolar] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Ctrl_Escolar] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Ctrl_Escolar] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Ctrl_Escolar] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Ctrl_Escolar] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Ctrl_Escolar] SET  ENABLE_BROKER 
GO
ALTER DATABASE [Ctrl_Escolar] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Ctrl_Escolar] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Ctrl_Escolar] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Ctrl_Escolar] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Ctrl_Escolar] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Ctrl_Escolar] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Ctrl_Escolar] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Ctrl_Escolar] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Ctrl_Escolar] SET  MULTI_USER 
GO
ALTER DATABASE [Ctrl_Escolar] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Ctrl_Escolar] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Ctrl_Escolar] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Ctrl_Escolar] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Ctrl_Escolar] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Ctrl_Escolar] SET QUERY_STORE = OFF
GO
USE [Ctrl_Escolar]
GO
/****** Object:  Table [dbo].[ALUMNOS]    Script Date: 17/01/2022 10:09:39 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ALUMNOS](
	[ID_Matricula] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](50) NULL,
	[Paterno] [varchar](50) NULL,
	[Materno] [varchar](50) NULL,
	[Tel] [nchar](10) NULL,
	[Email] [varchar](50) NULL,
	[ID_Grupo] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_Matricula] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CALIFICACIONES]    Script Date: 17/01/2022 10:09:39 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CALIFICACIONES](
	[ID_Materia] [int] NOT NULL,
	[ID_Matricula] [int] NOT NULL,
	[Calificacion] [float] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_Materia] ASC,
	[ID_Matricula] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DIRECTORIO]    Script Date: 17/01/2022 10:09:39 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DIRECTORIO](
	[ID_Materia] [int] NOT NULL,
	[ID_Maestro] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_Maestro] ASC,
	[ID_Materia] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[GRUPOS]    Script Date: 17/01/2022 10:09:39 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GRUPOS](
	[ID_Grupo] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](50) NULL,
	[Limite] [nchar](2) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_Grupo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HORARIOS]    Script Date: 17/01/2022 10:09:39 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HORARIOS](
	[ID_Horario] [int] IDENTITY(1,1) NOT NULL,
	[ID_Materia] [int] NOT NULL,
	[ID_Maestro] [int] NOT NULL,
	[Hora_Ini] [time](7) NULL,
	[Hora_Fin] [time](7) NULL,
	[ID_Grupo] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_Horario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MAESTROS]    Script Date: 17/01/2022 10:09:39 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MAESTROS](
	[ID_Maestro] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](50) NULL,
	[Paterno] [varchar](50) NULL,
	[Materno] [varchar](50) NULL,
	[Tel] [nchar](10) NULL,
	[Email] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_Maestro] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MATERIAS]    Script Date: 17/01/2022 10:09:39 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MATERIAS](
	[ID_Materia] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_Materia] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ALUMNOS]  WITH CHECK ADD FOREIGN KEY([ID_Grupo])
REFERENCES [dbo].[GRUPOS] ([ID_Grupo])
GO
ALTER TABLE [dbo].[CALIFICACIONES]  WITH CHECK ADD FOREIGN KEY([ID_Materia])
REFERENCES [dbo].[MATERIAS] ([ID_Materia])
GO
ALTER TABLE [dbo].[CALIFICACIONES]  WITH CHECK ADD FOREIGN KEY([ID_Matricula])
REFERENCES [dbo].[ALUMNOS] ([ID_Matricula])
GO
ALTER TABLE [dbo].[DIRECTORIO]  WITH CHECK ADD  CONSTRAINT [IDir_Maestro] FOREIGN KEY([ID_Maestro])
REFERENCES [dbo].[MAESTROS] ([ID_Maestro])
GO
ALTER TABLE [dbo].[DIRECTORIO] CHECK CONSTRAINT [IDir_Maestro]
GO
ALTER TABLE [dbo].[DIRECTORIO]  WITH CHECK ADD  CONSTRAINT [IDir_Materia] FOREIGN KEY([ID_Materia])
REFERENCES [dbo].[MATERIAS] ([ID_Materia])
GO
ALTER TABLE [dbo].[DIRECTORIO] CHECK CONSTRAINT [IDir_Materia]
GO
ALTER TABLE [dbo].[HORARIOS]  WITH CHECK ADD FOREIGN KEY([ID_Maestro], [ID_Materia])
REFERENCES [dbo].[DIRECTORIO] ([ID_Maestro], [ID_Materia])
GO
ALTER TABLE [dbo].[HORARIOS]  WITH CHECK ADD FOREIGN KEY([ID_Grupo])
REFERENCES [dbo].[GRUPOS] ([ID_Grupo])
GO
USE [master]
GO
ALTER DATABASE [Ctrl_Escolar] SET  READ_WRITE 
GO
